[package]
name = "rerast_macros"
version = "0.1.0"
description = "Macros for use in Rerast rules"
repository = "https://github.com/google/rerast"
authors = ["David Lattimore <dml@google.com>"]

[dependencies]
